[package]
name = "ktls-sys"
version = "1.0.2"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = """
FFI bindings for `linux/tls.h`
"""
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
